### ISSUE TITLE
Add murals from POW!WOW! San Jose Oct 2018

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/heartofthevalley#70]
A number of new murals were installed/created Oct 2018 by POW!WOW! San Jose and Empire Seven Studios art gallery. Here is a link to the list of [murals.](https://www.powwowsanjose.com/)

We need to update the `artworks-data/consolidated-artworks.json` and `js/art.js` file with this new information. Please check to make sure they are not already on the list before adding the data. 

In order to find the latitude and longitude, please look up the location on OpenStreetMaps: https://www.openstreetmap.org/

**Comment by Lyrratic** [comment]
Hello! If you're still accepting contributions, I'd be happy to take this on.

One clarification question: it looks like previously art has mostly been added by scraping sanjoseca.gov and assigning IDs at that point; as part of this change, would we need a way to programmatically assign IDs to manually added artwork listings?

**Comment by Kyle-Falconer** [comment]
@Lyrratic the `ID` is currently a SHA256 hash of the `artist`, `title`, and `sourceURL` fields, separated by a hyphen and prefixed with `art_`.

This is completely arbitrary and can be changed if needed, the only requirements are that it is unique for every art object and that it can be one-way hashed for repeatable IDs the next time it is scraped. The one-way hash is important because this allows for the art objects in the `artworks-overrides.json` file to be matched with the scraped version. The code is here:
https://github.com/codeforsanjose/heartofthevalley/blob/802280182f847c0156167a63c436c8804b80f182/lib/artwork.js#L25-L27

If you're planning to create this JSON file manually, you could call the `generateID()` function call on each art item just that file before it is consolidated with the other artwork on this step:
https://github.com/codeforsanjose/heartofthevalley/blob/802280182f847c0156167a63c436c8804b80f182/scripts/consolidate-artwork-files.js#L33-L37

Alternatively, you could do the artwork generation manually in the command line for each one (it looks like there are only about 30 to do from that website):
```
echo -n "art_someartist-sometitle-https://example.com/sometitle" | shasum -a 256
```
